-- Create and switch to the database

CREATE DATABASE IF NOT EXISTS SpotifyAnalytics;
USE SpotifyAnalytics;

CREATE TABLE IF NOT EXISTS TRACKS (
    Track_ID INT PRIMARY KEY,
    Track_Name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS MUSICALLITY (
    Music_ID INT PRIMARY KEY,
    Track_ID INT,
    FOREIGN KEY (Track_ID) REFERENCES TRACKS(Track_ID)
);

CREATE TABLE IF NOT EXISTS ARTISTS (
    ARTISTS_ID INT PRIMARY KEY,
    Track_ID INT,
    Artist_Name VARCHAR(255),
    FOREIGN KEY (Track_ID) REFERENCES TRACKS(Track_ID)
);

CREATE TABLE IF NOT EXISTS RHYTHM (
    RHYTHM_ID INT PRIMARY KEY,
    Track_ID INT,
    FOREIGN KEY (Track_ID) REFERENCES TRACKS(Track_ID)
);

CREATE TABLE IF NOT EXISTS STATS (
    STATS_ID INT PRIMARY KEY,
    TRACK_ID INT,
    POPULARITY INT,
    INSTRUMENTALNESS FLOAT,
    FOREIGN KEY (Track_ID) REFERENCES TRACKS(Track_ID)
);


CREATE TABLE IF NOT EXISTS TRACKKEYS (
    Key_ID INT PRIMARY KEY,
    Key_Value VARCHAR(255) NOT NULL,
    Mode VARCHAR(255),
    FOREIGN KEY (Key_ID) REFERENCES MUSICALLITY(Music_ID)
);

CREATE TABLE IF NOT EXISTS TEMPO (
    TEMPO_ID INT PRIMARY KEY,
    TEMPO FLOAT,
    TIME_SIGNATURE VARCHAR(255),
    FOREIGN KEY (TEMPO_ID) REFERENCES RHYTHM(RHYTHM_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCTION (
    PROD_ID INT PRIMARY KEY,
    STATS_ID INT,
    GENRE VARCHAR(255),
    DURATION_MS INT,
    FOREIGN KEY (STATS_ID) REFERENCES STATS(STATS_ID)
);

CREATE TABLE IF NOT EXISTS LISTENABILITY (
    LISTEN_ID INT PRIMARY KEY,
    STATS_ID INT,
    FOREIGN KEY (STATS_ID) REFERENCES STATS(STATS_ID)
);

CREATE TABLE IF NOT EXISTS LOUDNESS (
    LOUDNESS FLOAT PRIMARY KEY,
    ACOUSTICNESS FLOAT
);

CREATE TABLE IF NOT EXISTS DANCEBILITY (
    DANCEBILITY FLOAT PRIMARY KEY,
    LIVENESS FLOAT,
    VALENCE FLOAT
);
